name: yalla_harek
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4

  retrofit: ^3.0.1+1

  #Local database
  floor: ^1.2.0

  #UI
  flutter_hooks: ^0.18.3

  #DI
  get_it: ^7.2.0

  #State management
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  flutter_datetime_picker: ^1.5.1
  dartz: ^0.10.1

  #Whatsapp
  whatsapp_unilink: ^2.0.1+1
  url_launcher: ^6.0.20

  image_picker: ^0.8.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  floor_generator: ^1.2.0
  build_runner: ^2.1.2
  lint: ^1.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/